// Authoritative server-side portfolio dataset strictly compiled from Qayoom Akhtar's official resume and portfolio files.
// DO NOT invent or fabricate information outside of this dataset.

export const PORTFOLIO_CONTEXT = {
  personal: {
    name: "Qayoom Akhtar",
    primaryRole: "Full Stack Engineer",
    roles: [
      "Full Stack Engineer",
      "AI Application Engineer",
      "React & Next.js Engineer",
      "MERN Stack Developer",
    ],
    positioning: "Full Stack Engineer building modern full-stack and AI-integrated web applications.",
    experienceSummary: "Full Stack Engineer with 6+ months of experience building production web and AI-integrated applications combining React/Next.js frontends with Node.js/Express backends, LLM/RAG integrations, and scalable databases.",
    status: "Looking for Opportunities / Available for Full-Time Opportunities",
    stats: {
      projectsBuilt: "15+",
      aiIntegrations: "5+",
      coreFocus: "Full Stack Development",
    },
  },

  education: [
    {
      degree: "B.Tech in Computer Science Engineering",
      institution: "Chandigarh University, Mohali",
      years: "2022 – 2026",
    },
  ],

  experienceHistory: [
    {
      role: "Full Stack Development Intern",
      company: "Infotech Service",
      responsibilities: [
        "Developed responsive React UI components used across production features, focusing on reusability and performance.",
        "Integrated frontend with backend APIs end-to-end, improving perceived responsiveness and reducing server response time by 15–20%.",
        "Optimized application performance through component optimization, lazy loading, and efficient state management.",
        "Built and consumed RESTful APIs to enable seamless communication between frontend and backend services.",
      ],
    },
    {
      role: "AI & ML Trainee",
      company: "Chandigarh University",
      responsibilities: [
        "Built ML models on real-world datasets with data preprocessing, feature engineering, and evaluation using Python.",
        "Implemented classification and regression algorithms using Scikit-learn and evaluated models with standard performance metrics.",
      ],
    },
  ],

  contact: {
    email: "qayoomakhtar72@gmail.com",
    emailLink: "mailto:qayoomakhtar72@gmail.com",
    phone: "+91 9798413263",
    phoneLink: "tel:+919798413263",
    location: "Mohali, Punjab, India",
    portfolio: "https://qayoomakhtar.vercel.app",
    github: "https://github.com/test-Ois",
    linkedin: "https://www.linkedin.com/in/qayoom-akhtar",
    resume: "https://drive.google.com/drive/u/0/folders/1WayKbomGqVUlmhQbi9Y2GgXN-Q2V1IDL",
  },

  skills: {
    frontend: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript (ES6+)",
      "Tailwind CSS",
      "HTML5",
      "CSS3",
    ],
    backend: [
      "Node.js",
      "Express.js",
      "REST APIs",
      "Socket.IO (Real-time communication)",
      "JWT Authentication",
      "Firebase Authentication",
      "Server-Sent Events (SSE)",
    ],
    databases: [
      "MongoDB",
      "PostgreSQL",
      "Prisma ORM",
      "Redis",
      "Qdrant (Vector DB)",
    ],
    aiMl: [
      "LLM API Integration",
      "Retrieval-Augmented Generation (RAG)",
      "Vector Embeddings",
      "Prompt Engineering",
      "Semantic Search",
      "Multi-provider AI routing",
      "AI Application Development",
    ],
    tools: [
      "Git",
      "GitHub",
      "Vercel",
      "Postman",
      "Docker",
    ],
    concepts: [
      "System Design",
      "OOP",
      "DSA",
      "Performance Optimization",
      "Component Architecture",
    ],
  },

  projects: [
    {
      id: 1,
      title: "01 — AI Career Agent",
      category: "AI Career Platform",
      status: "Ongoing Project",
      isOngoing: true,
      description: "An AI-powered career platform designed to help users improve resumes, analyze job descriptions, optimize applications, generate career documents, manage job applications, and streamline the job-search workflow.",
      technologies: ["Next.js", "React", "Node.js", "Express", "PostgreSQL", "Neon", "Prisma", "Google OAuth"],
      features: [
        "Resume upload, multi-format parsing, and visual ATS scoring evaluation.",
        "Bullet-point optimization and job-specific resume tailoring.",
        "Job description requirement extraction and personalized cover letter generation.",
        "Ask AI career assistant for salary, interview preparation, and strategy.",
        "Kanban-style job application tracker, company notes, and automated workflows.",
        "Full-stack Next.js + Express /api/v1 architecture with PostgreSQL (Neon) and Prisma ORM.",
      ],
      githubUrl: "https://github.com/test-Ois",
      demoUrl: null,
      accent: "#8254EE",
    },
    {
      id: 2,
      title: "02 — InboxIQ AI",
      category: "AI-Powered Email Intelligence Platform",
      status: "Completed",
      isOngoing: false,
      description: "Full-stack architecture for an AI-powered email intelligence platform covering email analysis, message prioritization, semantic categorization, and spam/fraud detection.",
      technologies: ["Next.js", "NestJS", "PostgreSQL", "Prisma", "Gemini AI", "TypeScript"],
      features: [
        "Built full-stack architecture for an AI-powered email platform covering email analysis, categorization, and insight dashboards end-to-end.",
        "Designed scalable REST APIs backed by PostgreSQL/Prisma, ensuring clean data flow and type-safe integration.",
        "Integrated Gemini AI for real-time insights, prioritization, and spam/fraud flag detection.",
      ],
      githubUrl: "https://github.com/test-Ois/inboxiq-ai",
      demoUrl: null,
      accent: "#00C2FF",
    },
    {
      id: 3,
      title: "03 — Xynox AI",
      category: "AI Assistant Platform",
      status: "Completed",
      isOngoing: false,
      description: "A production-grade full-stack AI assistant platform featuring multi-provider AI routing, real-time streaming responses via Server-Sent Events (SSE), and RAG with PDF parsing and Qdrant vector database integration.",
      technologies: ["React", "Vite", "Node.js", "Express", "Firebase Auth", "Qdrant", "Groq AI", "NVIDIA AI", "Cerebras AI", "SSE", "Tailwind CSS"],
      features: [
        "Multi-provider AI routing with real-time streaming responses via Server-Sent Events (SSE).",
        "Retrieval-Augmented Generation (RAG) with PDF parsing, intelligent chunking, vector embeddings, and Qdrant vector DB.",
        "Secure Google Authentication using Firebase Auth with JWT-protected APIs.",
        "Conversational memory, prompt library, and markdown rendering optimizations.",
      ],
      githubUrl: "https://github.com/test-Ois/xynox-ai",
      demoUrl: null,
      accent: "#8254EE",
    },
    {
      id: 4,
      title: "04 — Qyro",
      category: "Full Stack E-Commerce Platform",
      status: "Completed",
      isOngoing: false,
      description: "A modern full-stack e-commerce web application featuring intelligent product search, personalized recommendations, comprehensive cart & order workflows, and a scalable MERN architecture.",
      technologies: ["Next.js", "Node.js", "MongoDB", "Express.js", "Tailwind CSS"],
      features: [
        "Intelligent product recommendations and search filtering.",
        "Secure authentication and full-stack MERN architecture.",
        "Cart and checkout state management with local persistence.",
      ],
      githubUrl: "https://github.com/test-Ois/qyro-ecommerce",
      demoUrl: null,
      accent: "#8254EE",
    },
    {
      id: 5,
      title: "05 — Game Galaxy Hub",
      category: "Multiplayer Gaming Platform",
      status: "Completed",
      isOngoing: false,
      description: "Real-time multiplayer gaming hub for Tic-Tac-Toe and Ludo featuring low-latency WebSocket rooms, live synchronization, chat connectivity using Socket.io, and fallback AI logic.",
      technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Zustand", "Socket.IO"],
      features: [
        "Low-latency WebSocket room creation and live player synchronization.",
        "Interactive real-time game state management, PvP and PvAI modes, and chat connectivity.",
      ],
      githubUrl: "https://github.com/test-Ois/game-galaxy-hub",
      demoUrl: "https://game-galaxy-hub.vercel.app/",
      accent: "#00C2FF",
    },
  ],
};
